@extends('layouts.app')
@section('title', 'Platform Reports')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-4 animate-slide-up">
    <div>
        <h2 style="font-weight: 600;" class="mb-1"><i class="bi bi-graph-up text-apple-accent"></i> Platform Reports</h2>
        <p class="mb-0" style="color: var(--apple-text-muted);">View, generate, and export platform analytics and SDG impact reports.</p>
    </div>
    @if(Auth::user()->isAdmin())
    <a href="{{ route('reports.create') }}" class="btn btn-ns-primary">
        <i class="bi bi-plus-circle"></i> Generate Report
    </a>
    @endif
</div>

@if(session('success'))
<div class="alert alert-success alert-dismissible fade show animate-slide-up" role="alert">
    {{ session('success') }}
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
</div>
@endif

<div class="card shadow-sm animate-slide-up">
    <div class="card-header d-flex justify-content-between align-items-center">
        <span><i class="bi bi-file-earmark-bar-graph text-apple-accent me-1"></i> Generated Reports List</span>
        <span class="badge border px-3 py-1" style="background-color: var(--apple-input-bg); color: var(--apple-text); border-color: var(--apple-border) !important; font-size: 0.75rem; font-weight: 500;">
            {{ $reports->total() }} Total Reports
        </span>
    </div>
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-hover align-middle mb-0">
                <thead>
                    <tr class="border-bottom" style="border-color: var(--apple-border) !important;">
                        <th class="ps-4 py-3 fw-semibold small" style="color: var(--apple-text-muted);">Report Title</th>
                        <th class="py-3 fw-semibold small" style="color: var(--apple-text-muted);">Type</th>
                        <th class="py-3 fw-semibold small" style="color: var(--apple-text-muted);">Generated By</th>
                        <th class="py-3 fw-semibold small" style="color: var(--apple-text-muted);">Report Date</th>
                        <th class="pe-4 py-3 fw-semibold small text-end" style="color: var(--apple-text-muted);">Actions</th>
                    </tr>
                </thead>
                <tbody>
                @forelse($reports as $report)
                <tr class="border-bottom" style="border-color: var(--apple-border) !important;">
                    <td class="ps-4">
                        <strong style="color: var(--apple-text);">
                            <a href="{{ route('reports.show', $report) }}" class="text-decoration-none" style="color: var(--apple-text);">{{ $report->title }}</a>
                        </strong>
                    </td>
                    <td>
                        <span class="badge badge-{{ $report->type === 'sdg_impact' ? 'success' : ($report->type === 'donation_summary' ? 'warning' : 'primary') }}">
                            @if($report->type === 'sdg_impact')
                                <i class="bi bi-globe me-1"></i> SDG Impact
                            @elseif($report->type === 'donation_summary')
                                <i class="bi bi-basket me-1"></i> Donation Summary
                            @else
                                <i class="bi bi-people me-1"></i> User Activity
                            @endif
                        </span>
                    </td>
                    <td style="color: var(--apple-text);">
                        <i class="bi bi-person me-1 text-apple-accent"></i>{{ $report->user->name ?? 'System' }}
                    </td>
                    <td class="small" style="color: var(--apple-text-muted);">
                        <i class="bi bi-calendar me-1"></i>{{ $report->report_date->format('d M Y, h:i A') }}
                    </td>
                    <td class="pe-4 text-end">
                        <div class="d-inline-flex align-items-center gap-2">
                            <a href="{{ route('reports.show', $report) }}" class="btn btn-sm btn-outline-light text-nowrap">
                                <i class="bi bi-eye"></i> View
                            </a>
                            <a href="{{ route('reports.export', $report) }}" class="btn btn-sm btn-outline-success text-nowrap">
                                <i class="bi bi-download"></i> Export
                            </a>
                            @if(Auth::user()->isAdmin())
                            <form method="POST" action="{{ route('reports.destroy', $report) }}" class="d-inline">
                                @csrf @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-outline-danger" onclick="return confirm('Delete this report?')">
                                    <i class="bi bi-trash"></i>
                                </button>
                            </form>
                            @endif
                        </div>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="5" class="text-center py-5" style="color: var(--apple-text-muted);">No reports generated yet.</td>
                </tr>
                @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="mt-4 animate-slide-up">{{ $reports->links() }}</div>
@endsection
