<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * User Model — Central entity supporting sub-roles: Donor, NGO, Admin.
 *
 * @property int $id
 * @property string $name
 * @property string $email
 * @property string $password
 * @property string $role  donor|ngo|admin
 * @property string $verification_status  pending|approved|rejected
 * @property string|null $organization_name
 * @property string|null $phone
 * @property string|null $address
 * @property string $notification_preference  email|sms|both
 */
class User extends Authenticatable
{
    use HasFactory, Notifiable;

    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'verification_status',
        'organization_name',
        'phone',
        'address',
        'notification_preference',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed', // Automatic Bcrypt hashing (Module 2 Security)
        ];
    }

    // ──────────────── Relationships ────────────────

    /** A user (Donor) can publish many donations. */
    public function donations(): HasMany
    {
        return $this->hasMany(Donation::class);
    }

    /** A user (NGO) can submit many claims. */
    public function claims(): HasMany
    {
        return $this->hasMany(Claim::class);
    }

    /** A user can upload many verification documents. */
    public function verificationDocuments(): HasMany
    {
        return $this->hasMany(VerificationDocument::class);
    }

    /** Reviews written by this user. */
    public function reviewsGiven(): HasMany
    {
        return $this->hasMany(Review::class, 'reviewer_id');
    }

    /** Reviews received by this user. */
    public function reviewsReceived(): HasMany
    {
        return $this->hasMany(Review::class, 'reviewee_id');
    }

    /** Notifications belonging to this user. */
    public function notifications(): HasMany
    {
        return $this->hasMany(Notification::class);
    }

    /** System logs associated with this user's actions. */
    public function systemLogs(): HasMany
    {
        return $this->hasMany(SystemLog::class);
    }

    /** Reports generated by this user. */
    public function reports(): HasMany
    {
        return $this->hasMany(Report::class);
    }

    /** Inventory locations owned by this user. */
    public function inventoryLocations(): HasMany
    {
        return $this->hasMany(InventoryLocation::class);
    }

    // ──────────────── Helper Methods ────────────────

    public function isDonor(): bool
    {
        return $this->role === 'donor';
    }

    public function isNgo(): bool
    {
        return $this->role === 'ngo';
    }

    public function isAdmin(): bool
    {
        return $this->role === 'admin';
    }

    public function isVerified(): bool
    {
        return $this->verification_status === 'approved';
    }

    /** Calculate average trust rating from reviews received. */
    public function averageRating(): float
    {
        return (float) $this->reviewsReceived()->avg('rating') ?: 0.0;
    }
}
